'use client'
import Navbar from "@/components/layout/navbar";
import Sidebar from "@/components/layout/sidebar/sidebar";
import { useState } from "react";


const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [openBar, setOpenBar] = useState(false)





  return (
      <>
        <div className={`${!openBar && 'hidden'} lg:hidden fixed inset-0 z-20 bg-black/[0.5]`} onClick={e => setOpenBar(false)}>
        </div>
        <Navbar setOpenBar={setOpenBar} />
        <Sidebar openBar={openBar} setOpenBar={setOpenBar} />
        <div className='lg:pl-[288px] lg:pt-[100px] pt-[112px] h-screen overflow-y-auto scrollbar-hide'>
        {children}
        </div>
      </>
  )
}